# Generated by Django 4.1.7 on 2023-03-13 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_record_habit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('date', 'habit')},
        ),
    ]
