# Generated by Django 4.1.7 on 2023-03-15 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_record_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='goal_number',
            new_name='number_completed',
        ),
    ]
