# Generated by Django 4.1.7 on 2023-03-16 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_record_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='observers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
