# Generated by Django 4.1.7 on 2023-03-16 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_habit_observers'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='habits_i_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habit',
            name='observers',
            field=models.ManyToManyField(blank=True, null=True, related_name='habits_i_am_observing', to=settings.AUTH_USER_MODEL),
        ),
    ]
